# Build stage
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Nginx stage
FROM nginx:alpine

COPY nginx.qa.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html

ENV NGINX_PORT=6080
ENV API_URL=https://payrollserver.cenzios.com/api/

EXPOSE 6080
EXPOSE 5090

CMD ["/bin/sh","-c","envsubst '$NGINX_PORT $API_URL' < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]